const products = [
     // T-Shirts
     { id: 1, name: 'Classic White Cotton Tee', price: 499, category: 'T-Shirts', image: 'https://tse2.mm.bing.net/th?id=OIP.vQYmUfgCU4PQtZq4UARj_gAAAA&pid=Api&P=0&h=180' },
     { id: 2, name: 'Graphic Printed Tee', price: 699, category: 'T-Shirts', image: 'https://i.pinimg.com/originals/ed/f6/da/edf6daf2d390848de335e0a9fa6dd090.jpg' },
     { id: 3, name: 'Oversized Retro Tee', price: 799, category: 'T-Shirts', image: 'https://i.pinimg.com/originals/df/08/50/df08507910912d00038246f2bf70d4c6.jpg' },
     { id: 4, name: 'Color Block Tee', price: 649, category: 'T-Shirts', image: 'https://img.guess.com/image/upload/f_auto,q_auto,fl_strip_profile,w_800,c_scale/v1/NA/Style/ECOMM/X3RP22KC4M2-JBLK' },
     { id: 5, name: 'Tie-Dye Tee', price: 899, category: 'T-Shirts', image: 'https://i5.walmartimages.com/asr/93286917-b7d7-4122-9b62-2e58a578cf89.0c1a492aad9e73d1d06d9c8853ccfe8d.jpeg' },
     { id: 6, name: 'Striped Casual Tee', price: 599, category: 'T-Shirts', image: 'https://image26.stylesimo.com/o_img/2018/05/29/254988-10548316/women-s-casual-loose-striped-short-sleeve-round-neck-pullover-tee-shirt.jpg' },
     { id: 7, name: 'Slim Fit Crew Neck Tee', price: 749, category: 'T-Shirts', image: 'https://lsco.scene7.com/is/image/lsco/levis/clothing/795410003-alt4-pdp.jpg?fmt=jpeg&qlt=70&resMode=bisharp&fit=crop,0&op_usm=0.6,0.6,8&wid=2000&hei=1852' },
     { id: 8, name: 'V-Neck Summer Tee', price: 549, category: 'T-Shirts', image: 'https://cbu01.alicdn.com/img/ibank/2018/773/581/8688185377_2107390325.jpg' },
     { id: 9, name: 'Pocketed Basic Tee', price: 499, category: 'T-Shirts', image: 'https://thedailylab.co/cdn/shop/files/Screenshot2023-06-02at3.19.48PM_1500x.png?v=1688442424' },
     { id: 10, name: 'Longline Urban Tee', price: 799, category: 'T-Shirts', image: 'https://i.pinimg.com/originals/60/2e/11/602e112fce3bd80eabc3853f5532f43b.jpg' },

     // Shirts
     { id: 11, name: 'Slim Fit Formal Shirt', price: 999, category: 'Shirts', image: 'https://tse3.mm.bing.net/th?id=OIP.2smO6EbmQVqr37cYtqkVXQHaJ1&pid=Api&P=0&h=180' },
     { id: 12, name: 'Floral Print Casual Shirt', price: 849, category: 'Shirts', image: 'https://images.bestsellerclothing.in/data/vero-moda/26-apr-2023/224087303_g0.jpg?width=1080&height=1355&mode=fill&fill=blur&format=auto&dpr=1.2' },
     { id: 13, name: 'Plaid Checkered Shirt', price: 749, category: 'Shirts', image: 'https://tse4.mm.bing.net/th?id=OIP.NVirWILMsxnj5kp4I4fbdQHaHa&pid=Api&P=0&h=180' },
     { id: 14, name: 'Denim Button-Up Shirt', price: 1299, category: 'Shirts', image: 'https://assets.torrid.com/is/image/torrid/11317903_hi?$td_pdp_zoom_image$' },
     { id: 15, name: 'Mandarin Collar Shirt', price: 899, category: 'Shirts', image: 'https://tse4.mm.bing.net/th?id=OIP.49HwouogFqr5XqVh4mOveQHaJQ&pid=Api&P=0&h=180' },
     { id: 16, name: 'Short Sleeve Cuban Shirt', price: 799, category: 'Shirts', image: 'http://cdn.shopify.com/s/files/1/0293/9277/products/03-01-23_CB_DJ_14-18-37_72_ZDF01K310007_Black_P_16101_WG_1200x1200.jpg?v=1677792842' },
     { id: 17, name: 'Linen Summer Shirt', price: 1199, category: 'Shirts', image: 'https://www.madetrade.com/cdn/shop/products/scarlett-linen-summer-shirt-shirts-amourlinen-m-sage-green-551713_160x.webp?v=1689121125' },
     { id: 18, name: 'Satin Partywear Shirt', price: 1599, category: 'Shirts', image: 'https://i.pinimg.com/originals/88/4a/5d/884a5d7693d8164f486690d0b5365d7b.jpg' },
     { id: 19, name: 'Pinstriped Office Shirt', price: 1049, category: 'Shirts', image: 'https://welbornecorporateuniforms.com.au/wp-content/uploads/2019/02/JK_462_Gunmetal-468x610.jpg' },
     { id: 20, name: 'Ombre Dyed Shirt', price: 1099, category: 'Shirts', image: 'https://www.jiomart.com/images/product/500x630/469369925_bluewhite/ombre-dyed-slim-fit-shirt-model-469369925_bluewhite-0-202301081734.jpg' },
       

     // Jeans
     { id: 21, name: 'Skinny Fit Stretch Jeans', price: 1399, category: 'Jeans', image: '' },
     { id: 22, name: 'Ripped Distressed Jeans', price: 1499, category: 'Jeans', image: '' },
     { id: 23, name: 'High-Waisted Mom Jeans', price: 1299, category: 'Jeans', image: '' },
     { id: 24, name: 'Slim Fit Black Jeans', price: 1399, category: 'Jeans', image: '' },
     { id: 25, name: 'Boyfriend Relaxed Jeans', price: 1499, category: 'Jeans', image: '' },
     { id: 26, name: 'Straight-Leg Vintage Jeans', price: 1599, category: 'Jeans', image: '' },
     { id: 27, name: 'Bootcut Blue Jeans', price: 1299, category: 'Jeans', image: '' },
     { id: 28, name: 'Cropped Ankle Jeans', price: 1199, category: 'Jeans', image: '' },
     { id: 29, name: 'Flare Stretchable Jeans', price: 1699, category: 'Jeans', image: '' },
     { id: 30, name: 'Acid-Wash Skinny Jeans', price: 1399, category: 'Jeans', image: '' },

     // Trousers
     { id: 31, name: 'Slim-Fit Chinos', price: 1299, category: 'Trousers', image: '' },
     { id: 32, name: 'Cargo Utility Pants', price: 1499, category: 'Trousers', image: '' },
     { id: 33, name: 'Wide-Leg Palazzo Trousers', price: 1399, category: 'Trousers', image: '' },
     { id: 34, name: 'High-Waisted Paperbag Pants', price: 1499, category: 'Trousers', image: '' },
     { id: 35, name: 'Cropped Ankle Trousers', price: 1299, category: 'Trousers', image: '' },
     { id: 36, name: 'Pleated Formal Pants', price: 1599, category: 'Trousers', image: '' },
     { id: 37, name: 'Jogger-Style Trousers', price: 1199, category: 'Trousers', image: '' },
     { id: 38, name: 'Stretchable Corduroy Pants', price: 1499, category: 'Trousers', image: '' },
     { id: 39, name: 'Textured Linen Pants', price: 1399, category: 'Trousers', image: '' },
     { id: 40, name: 'Tailored Workwear Pants', price: 1699, category: 'Trousers', image: '' },

     // Jackets
     { id: 41, name: 'Classic Denim Jacket', price: 1999, category: 'Jackets', image: '' },
     { id: 42, name: 'Faux Leather Biker Jacket', price: 2999, category: 'Jackets', image: '' },
     { id: 43, name: 'Quilted Winter Puffer Jacket', price: 2499, category: 'Jackets', image: '' },
     { id: 44, name: 'Oversized Hooded Jacket', price: 2299, category: 'Jackets', image: '' },
     { id: 45, name: 'Cropped Bomber Jacket', price: 1799, category: 'Jackets', image: '' },
     { id: 46, name: 'Longline Trench Coat', price: 3499, category: 'Jackets', image: '' },
     { id: 47, name: 'Fleece Zip-Up Jacket', price: 1599, category: 'Jackets', image: '' },
     { id: 48, name: 'Reversible Casual Jacket', price: 1999, category: 'Jackets', image: '' },
     { id: 49, name: 'Varsity Letterman Jacket', price: 1899, category: 'Jackets', image: '' },
     { id: 50, name: 'Wool-Blend Double-Breasted Coat', price: 3999, category: 'Jackets', image: '' },

     // Hoodies & Sweatshirts
     { id: 51, name: 'Pullover Fleece Hoodie', price: 1299, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 52, name: 'Zip-Up Sports Hoodie', price: 1499, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 53, name: 'Oversized Graphic Hoodie', price: 1599, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 54, name: 'Color Block Hoodie', price: 1399, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 55, name: 'Cropped Sweatshirt', price: 1199, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 56, name: 'Ribbed Hem Crewneck Sweatshirt', price: 1299, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 57, name: 'Tie-Dye Pullover Hoodie', price: 1499, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 58, name: 'Embroidered Logo Sweatshirt', price: 1599, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 59, name: 'Kangaroo Pocket Hoodie', price: 1499, category: 'Hoodies & Sweatshirts', image: '' },
     { id: 60, name: 'Thermal Knit Hoodie', price: 1699, category: 'Hoodies & Sweatshirts', image: '' },

     // Shorts
     { id: 81, name: 'Classic Denim Shorts', price: 999, category: 'Shorts', image: '' },
     { id: 82, name: 'High-Waisted Mom Shorts', price: 1199, category: 'Shorts', image: '' },
     { id: 83, name: 'Linen Drawstring Shorts', price: 899, category: 'Shorts', image: '' },
     { id: 84, name: 'Athletic Track Shorts', price: 799, category: 'Shorts', image: '' },
     { id: 85, name: 'Paperbag Belted Shorts', price: 1099, category: 'Shorts', image: '' },
     { id: 86, name: 'Pleated Formal Shorts', price: 1299, category: 'Shorts', image: '' },
     { id: 87, name: 'Cuffed Roll-Up Shorts', price: 999, category: 'Shorts', image: '' },
     { id: 88, name: 'Ripped Casual Shorts', price: 1199, category: 'Shorts', image: '' },
     { id: 89, name: 'Utility Cargo Shorts', price: 1299, category: 'Shorts', image: '' },
     { id: 90, name: 'Satin Lounge Shorts', price: 999, category: 'Shorts', image: '' },

     // Activewear
     { id: 101, name: 'Moisture-Wicking Tank Top', price: 799, category: 'Activewear', image: '' },
     { id: 102, name: 'Compression Fit Leggings', price: 1299, category: 'Activewear', image: '' },
     { id: 103, name: 'Mesh Insert Sports Bra', price: 999, category: 'Activewear', image: '' },
     { id: 104, name: 'Lightweight Running Shorts', price: 699, category: 'Activewear', image: '' },
     { id: 105, name: 'Fleece Lined Track Pants', price: 1499, category: 'Activewear', image: '' },
     { id: 106, name: 'Reflective Windbreaker', price: 1999, category: 'Activewear', image: '' },
     { id: 107, name: 'High-Impact Sports Bra', price: 1299, category: 'Activewear', image: '' },
     { id: 108, name: 'Ribbed Yoga Set', price: 1999, category: 'Activewear', image: '' },
     { id: 109, name: 'Seamless Workout Tee', price: 899, category: 'Activewear', image: '' },
     { id: 110, name: 'Gym Stringer Vest', price: 699, category: 'Activewear', image: '' },

     // Sleepwear
     { id: 111, name: 'Cotton Pajama Set', price: 1299, category: 'Sleepwear', image: '' },
     { id: 112, name: 'Satin Nightgown', price: 1999, category: 'Sleepwear', image: '' },
     { id: 113, name: 'Flannel Sleep Shirt', price: 999, category: 'Sleepwear', image: '' },
     { id: 114, name: 'Fleece Lounge Pants', price: 1199, category: 'Sleepwear', image: '' },
     { id: 115, name: 'Silk Camisole Set', price: 2499, category: 'Sleepwear', image: '' },
     { id: 116, name: 'Graphic Print Night Tee', price: 899, category: 'Sleepwear', image: '' },
     { id: 117, name: 'Short-Sleeve Pajama Dress', price: 1399, category: 'Sleepwear', image: '' },
     { id: 118, name: 'Velvet Robe Set', price: 1799, category: 'Sleepwear', image: '' },
     { id: 119, name: 'Button-Up Pajama Shirt', price: 1099, category: 'Sleepwear', image: '' },
     { id: 120, name: 'Thermal Long Johns', price: 1299, category: 'Sleepwear', image: '' },


     // Winterwear
     { id: 131, name: 'Cable Knit Sweater', price: 1499, category: 'Winterwear', image: '' },
     { id: 132, name: 'Turtleneck Pullover', price: 1599, category: 'Winterwear', image: '' },
     { id: 133, name: 'Woolen Overcoat', price: 3499, category: 'Winterwear', image: '' },
     { id: 134, name: 'Sherpa Lined Hoodie', price: 2299, category: 'Winterwear', image: '' },
     { id: 135, name: 'Knitted Cardigan', price: 1899, category: 'Winterwear', image: '' },
     { id: 136, name: 'Fleece Joggers', price: 1399, category: 'Winterwear', image: '' },
     { id: 137, name: 'Chunky Oversized Scarf', price: 899, category: 'Winterwear', image: '' },
     { id: 138, name: 'Beanie and Gloves Set', price: 999, category: 'Winterwear', image: '' },
     { id: 139, name: 'Fur-Lined Ankle Boots', price: 2499, category: 'Winterwear', image: '' },
     { id: 140, name: 'Thermal Base Layer', price: 1299, category: 'Winterwear', image: '' },

     // Accessories
     { id: 141, name: 'Leather Crossbody Bag', price: 1999, category: 'Accessories', image: '' },
     { id: 142, name: 'Fedora Hat', price: 899, category: 'Accessories', image: '' },
     { id: 143, name: 'Chunky Knit Scarf', price: 699, category: 'Accessories', image: '' },
     { id: 144, name: 'Metal Frame Sunglasses', price: 1499, category: 'Accessories', image: '' },
     { id: 145, name: 'Minimalist Gold Necklace', price: 1299, category: 'Accessories', image: '' },
     { id: 146, name: 'Studded Leather Belt', price: 799, category: 'Accessories', image: '' },
     { id: 147, name: 'Faux Leather Wallet', price: 999, category: 'Accessories', image: '' },
     { id: 148, name: 'Hoop Earrings Set', price: 699, category: 'Accessories', image: '' },
     { id: 149, name: 'Crystal Embellished Hair Clip', price: 599, category: 'Accessories', image: '' },
     { id: 150, name: 'Classic Analog Watch', price: 2499, category: 'Accessories', image: '' },

     // Footwear
     { id: 151, name: 'White Leather Sneakers', price: 2999, category: 'Footwear', image: '' },
     { id: 152, name: 'Suede Loafers', price: 2199, category: 'Footwear', image: '' },
     { id: 153, name: 'Chunky Platform Boots', price: 3499, category: 'Footwear', image: '' },
     { id: 154, name: 'Slip-On Canvas Shoes', price: 1299, category: 'Footwear', image: '' },
     { id: 155, name: 'Open-Toe Block Heels', price: 1799, category: 'Footwear', image: '' },
     { id: 156, name: 'Flip-Flop Sandals', price: 499, category: 'Footwear', image: '' },
     { id: 157, name: 'Strappy Gladiator Flats', price: 1299, category: 'Footwear', image: '' },
     { id: 158, name: 'Embellished Pumps', price: 2399, category: 'Footwear', image: '' },
     { id: 159, name: 'Lace-Up Hiking Boots', price: 2799, category: 'Footwear', image: '' },
     { id: 160, name: 'Knitted Slip-On Shoes', price: 1499, category: 'Footwear', image: '' },

     // Seasonal Specials
     { id: 171, name: 'Christmas Themed Sweaters', price: 1799, category: 'Seasonal Specials', image: '' },
     { id: 172, name: 'Summer Straw Hats', price: 899, category: 'Seasonal Specials', image: '' },
     { id: 173, name: 'Rainproof Trench Coats', price: 2499, category: 'Seasonal Specials', image: '' },
     { id: 174, name: 'Fall Leather Boots', price: 2999, category: 'Seasonal Specials', image: '' },
     { id: 175, name: 'Halloween Printed Tees', price: 799, category: 'Seasonal Specials', image: '' },
     { id: 176, name: 'Patriotic Print Tops', price: 1099, category: 'Seasonal Specials', image: '' },
     { id: 177, name: 'Floral Sundresses', price: 1499, category: 'Seasonal Specials', image: '' },
     { id: 178, name: 'New Year’s Eve Dresses', price: 2499, category: 'Seasonal Specials', image: '' },
     { id: 179, name: 'Valentine’s Day Red Shirts', price: 999, category: 'Seasonal Specials', image: '' },
     { id: 180, name: 'Spring Pastel Hoodies', price: 1599, category: 'Seasonal Specials', image: '' },
 
     // Partywear
     { id: 161, name: 'Sequined Evening Dress', price: 3999, category: 'Partywear', image: '' },
     { id: 162, name: 'Velvet Blazer', price: 2499, category: 'Partywear', image: '' },
     { id: 163, name: 'Satin Maxi Gown', price: 3499, category: 'Partywear', image: '' },
     { id: 164, name: 'Glitter Bodycon Dress', price: 2199, category: 'Partywear', image: '' },
     { id: 165, name: 'Metallic Midi Skirt', price: 1499, category: 'Partywear', image: '' },
     { id: 166, name: 'Crystal Embellished Clutch', price: 1599, category: 'Partywear', image: '' },
     { id: 167, name: 'Chiffon Wrap Dress', price: 1799, category: 'Partywear', image: '' },
     { id: 168, name: 'Silk Pocket Square', price: 499, category: 'Partywear', image: '' },
     { id: 169, name: 'Beaded Necklace', price: 899, category: 'Partywear', image: '' },
     { id: 170, name: 'Stiletto Heels', price: 2599, category: 'Partywear', image: '' },
    
     // Ethnic Wear
     { id: 91, name: 'Embroidered Kurta Set', price: 2499, category: 'Ethnic Wear', image: '' },
     { id: 92, name: 'Anarkali Gown', price: 2999, category: 'Ethnic Wear', image: '' },
     { id: 93, name: 'Cotton Printed Saree', price: 1799, category: 'Ethnic Wear', image: '' },
     { id: 94, name: 'Banarasi Silk Dupatta', price: 1499, category: 'Ethnic Wear', image: '' },
     { id: 95, name: 'Brocade Lehenga Set', price: 3999, category: 'Ethnic Wear', image: '' },
     { id: 96, name: 'Kurta with Churidar Pants', price: 2299, category: 'Ethnic Wear', image: '' },
     { id: 97, name: 'Angrakha Style Tunic', price: 1899, category: 'Ethnic Wear', image: '' },
     { id: 98, name: 'Floral Palazzo Suit', price: 2599, category: 'Ethnic Wear', image: '' },
     { id: 99, name: 'Jacket Style Sherwani', price: 4999, category: 'Ethnic Wear', image: '' },
     { id: 100, name: 'Handwoven Jute Saree', price: 1999, category: 'Ethnic Wear', image: '' },
     
     // Swimwear
     { id: 121, name: 'High-Waisted Bikini Set', price: 1499, category: 'Swimwear', image: 'https://thewearness.com/cdn/shop/products/197highwaistbikiniblack_1024x1024.jpg?v=1681403178' },
     { id: 122, name: 'One-Shoulder Swimsuit', price: 1999, category: 'Swimwear', image: 'https://www.bing.com/images/blob?bcid=SzZy.9ehxNMHqxcxoNWLuD9SqbotqVTdP9M' },
     { id: 123, name: 'Mesh Panel Monokini', price: 1799, category: 'Swimwear', image: 'https://gloimg.zafcdn.com/zaful/pdm-product-pic/Clothing/2020/07/14/source-img/20200714201418_5f0da19acb350.jpg?impolicy=high' },
     { id: 124, name: 'Board Shorts', price: 999, category: 'Swimwear', image: 'https://www.animal.co.uk/cdn/shop/files/053638_bla_animal_brett_recycled_mens_boardshorts_anl_ecom_lifestyle_ss23_01_696x.jpg?v=1692271176' },
     { id: 125, name: 'Tankini Top and Bottom', price: 1599, category: 'Swimwear', image: 'https://d1flfk77wl2xk4.cloudfront.net/Assets/24/409/XXL_p0209740924.jpg' },
     { id: 126, name: 'Crochet Beach Cover-Up', price: 1299, category: 'Swimwear', image: 'https://www.thebeachcompany.in/cdn/shop/files/Blue_1_800x.jpg?v=1717138745' },
     { id: 127, name: 'Racerback Swim Dress', price: 1899, category: 'Swimwear', image: 'https://m.media-amazon.com/images/I/719AwTDmo9L._AC_SY741_.jpg' },
     { id: 128, name: 'Cut-Out Swimsuit', price: 1699, category: 'Swimwear', image: 'https://cdn.platform.next/Common/Items/Default/Default/ItemImages/3_4Ratio/AltItemShot/366x488/707139s.jpg' },
     { id: 129, name: 'Swim Trunks', price: 899, category: 'Swimwear', image: 'https://www.shoplasc.com/v3/prld.xlg?partno=17127&width=498&view=img1' },
     { id: 130, name: 'Bandeau Bikini Top', price: 1199, category: 'Swimwear', image: 'https://cdnd.lystit.com/photos/2012/03/08/seafolly-orchid-seafolly-tea-rose-long-line-bandeau-bikini-top-product-1-3031247-636526010.jpeg' },
     
     // Dresses
     { id: 61, name: 'Floral Maxi Dress', price: 1799, category: 'Dresses', image: 'https://i.pinimg.com/originals/6b/78/73/6b7873b3f0f2d21e4676ca0ddb0996ee.jpg' },
     { id: 62, name: 'Satin Slip Dress', price: 1999, category: 'Dresses', image: 'https://i.pinimg.com/originals/84/d4/cd/84d4cdacaf26844ff01b9ce87abd674f.jpg' },
     { id: 63, name: 'Off-Shoulder Cocktail Dress', price: 2499, category: 'Dresses', image: 'https://th.bing.com/th/id/OIP.ADPfT4X3ERh-YCtfW-8G2QHaLH?rs=1&pid=ImgDetMain' },
     { id: 64, name: 'Bodycon Evening Dress', price: 2299, category: 'Dresses', image: 'https://th.bing.com/th/id/OIP.BYDw8l7InUQH5ylRaEFvOgHaJ4?rs=1&pid=ImgDetMain' },
     { id: 65, name: 'Puff-Sleeve Mini Dress', price: 1599, category: 'Dresses', image: 'https://images.urbndata.com/is/image/Anthropologie/4130729390008_049_b?$a15-pdp-detail-shot$&fit=constrain&qlt=80&wid=640' },
     { id: 66, name: 'Wrap Tie-Waist Dress', price: 1899, category: 'Dresses', image: 'https://i.pinimg.com/originals/9e/23/c6/9e23c687285eba5a93f67037feafae60.jpg' },
     { id: 67, name: 'Lace A-Line Dress', price: 2599, category: 'Dresses', image: 'https://th.bing.com/th/id/OIP.fZzEAVUSR-26r5lVRiTazQAAAA?rs=1&pid=ImgDetMain' },
     { id: 68, name: 'Denim Shirt Dress', price: 1799, category: 'Dresses', image: 'https://i.pinimg.com/originals/a2/21/e1/a221e1cafbc9c06d4e4943a4555cd1a5.jpg' },
     { id: 69, name: 'Pleated Midi Dress', price: 2099, category: 'Dresses', image: 'https://cdnd.lystit.com/photos/ad12-2016/03/15/topshop-dusty-pink-metallic-lame-pleated-midi-dress-pink-product-4-441986367-normal.jpeg' },
     { id: 70, name: 'Boho Style Tiered Dress', price: 1699, category: 'Dresses', image: 'https://shop.gabrielleparker.com/wp-content/uploads/2022/09/Boho-Tiered-dress-in-Ginger-Gold-mix-2-scaled.jpg' },
     { id: 185, name: 'Neckline Ruched Midi Dress', price: 1999, category:'Dresses', image:'https://dtdz5ym1pqo86.cloudfront.net/sites/files/mikayla/images/products/202401/dsc00187-enhanced-nr.jpg'},
     { id: 186, name: 'Long Sleeve Midi Dress', price: 1999, category:'Dresses', image:'https://shop.gabrielleparker.com/wp-content/uploads/2022/11/HOLLY-DRESS-GOLD-FLOWER-BLACK-SIDE-FULL-1024x1536.jpg'},
     { id: 187, name: 'Boho Style Maxi Dress', price: 1899, category: 'Dresses', image: 'https://www.lulus.com/images/product/xlarge/5333796_978262.jpg?w=560' },
     { id: 188, name: 'Net A-Line Wedding Dress', price: 2999, category: 'Dresses', image: 'https://www.jasminebridal.com/productimg/bridal-dresses-F211011-F.jpg' },

     // Skirts
     { id: 71, name: 'High-Waist Pencil Skirt', price: 1299, category: 'Skirts', image: 'https://i.pinimg.com/736x/21/05/d1/2105d1ac38288de5a2b22c9b3c961481.jpg' },
     { id: 72, name: 'Plaid Pleated Skirt', price: 1499, category: 'Skirts', image: 'https://th.bing.com/th/id/OIP.uK76lqPiu-Fi1EQ0MaUtJQAAAA?rs=1&pid=ImgDetMain' },
     { id: 73, name: 'Satin Wrap Skirt', price: 1799, category: 'Skirts', image: 'https://i.pinimg.com/736x/6f/28/7a/6f287acb581d86778832867e529b702f.jpg' },
     { id: 74, name: 'A-Line Button-Up Skirt', price: 1399, category: 'Skirts', image: 'https://cdn.tobi.com/product_images/md/4/navy-lydia-linen-crop-halter-top@2x.jpg' },
     { id: 75, name: 'Layered Ruffle Skirt', price: 1599, category: 'Skirts', image: 'https://th.bing.com/th/id/OIP.3sZinJ_UleT64fHSSGRTfQHaIZ?rs=1&pid=ImgDetMain' },
     { id: 76, name: 'Leather Mini Skirt', price: 1899, category: 'Skirts', image: 'https://i.pinimg.com/736x/9a/a3/80/9aa3800c16bee8e5f20a392428179749.jpg' },
     { id: 77, name: 'Maxi Tiered Skirt', price: 1499, category: 'Skirts', image: 'https://images-bucket.bonanzastatic.com/afu/images/003a/5dbd/070b_8128175199/tulle_skirt_maxi_tiered_6.jpg' },
     { id: 78, name: 'Asymmetrical Hem Skirt', price: 1799, category: 'Skirts', image: 'https://th.bing.com/th/id/OIP.k7aqWRsxjvsoYnnyprqZbgHaJ4?rs=1&pid=ImgDetMain' },
     { id: 79, name: 'Knit Bodycon Skirt', price: 1299, category: 'Skirts', image: 'https://th.bing.com/th/id/OIP.dltgwuYQu9dbITylP3XGgAHaI4?rs=1&pid=ImgDetMain' },
     { id: 80, name: 'Floral Printed Midi Skirt', price: 1699, category: 'Skirts', image: 'https://www.lulus.com/images/product/xlarge/3488270_685242.jpg' },
     { id: 181, name: 'Corduroy Mini Skirt', price: 1599, category:'Skirts', image:'https://i.pinimg.com/originals/75/cc/88/75cc88a63b6b0b275ba5fc8ab0658ff9.jpg'},
     { id: 182, name: 'Faux Suede Mini Skirt', price: 1399, category:'Skirts', image:'https://www.lulus.com/images/product/xlarge/3014050_536842.jpg?w=375&hdpi=1'},
     { id: 183, name: 'Floral Print Pleated Skirt', price: 1199, category:'Skirts', image:'https://i.pinimg.com/736x/68/b2/23/68b223e26606cf38fe337cce41caca5c--floral-print-skirt-floral-skirts.jpg'},
     { id: 184, name: 'Full Maxi Skirt', price: 1199, category:'Skirts', image:'https://cdn.shopify.com/s/files/1/0424/4065/products/059_-_20190619-Morning-Lavender-Nancy-Ivory-Knit-Cami_d9ccab5f-778c-4cef-8085-50866f4af7c7_1800x1800.jpg?v=1592369594'}
];
export default products; // Default export
